### ISSUE TITLE
update to version 4.19

### ISSUE THREAD

**Issue by alculete** [snapcrafters/eclipse#38] opened 2021-06-27 12:25 UTC
Please update eclipse to 4.19. Wasn't suppose for edge channel to get eclipse.org update automatically?

**Comment by agmckee** [comment] 2021-09-30 19:19
Edge channel is now 4.21.0 so I think this issue can be closed.

**Comment by alculete** [comment] 2021-10-05 17:46
Edge version is not running for me
```

!SESSION 2021-10-05 18:52:48.180 -----------------------------------------------
eclipse.buildId=4.21.0.I20210906-0500
java.version=16.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.osgi 4 0 2021-10-05 18:53:00.990
!MESSAGE Application error
!STACK 1
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-pi4-gtk-4946r21 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	no swt-pi4-gtk in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	no swt-pi4 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	Can't load library: /home/user/.swt/lib/linux/x86_64/libswt-pi4-gtk-4946r21.so
	Can't load library: /home/user/.swt/lib/linux/x86_64/libswt-pi4-gtk.so
	Can't load library: /home/user/.swt/lib/linux/x86_64/libswt-pi4.so

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:348)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:257)
	at org.eclipse.swt.internal.gtk.OS.<clinit>(OS.java:95)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:209)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:155)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:165)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:726)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:168)
	at org.eclipse.ui.internal.ide.application.IDEApplication.createDisplay(IDEApplication.java:182)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:125)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by agmckee** [comment] 2021-10-05 19:45
Hey @alculete sorry to hear that. Can you give some more details about your OS e.g. what distro? This might help me reproduce this.

**Comment by alculete** [comment] 2021-10-06 06:30
I'm using Ubuntu 21.04. If I rollback to stable release everything works fine

**Comment by agmckee** [comment] 2021-10-06 10:59
Thanks. I've been able to reproduce that on a fresh install of 21.04, I'll investigate further.

**Comment by alculete** [comment] 2021-10-13 18:56
any update?

**Comment by agmckee** [comment] 2021-10-13 19:22
Not really, no. I looked into it on the weekend and I'm quite stumped at the moment. This version code, swt-pi4-gtk-4946r21, is a bit of a red herring by the way as Eclipse will generate a fatal exception for loading swt-pi4 when it's already tried loading swt-pi3. See https://git.eclipse.org/c/gerrit/platform/eclipse.platform.swt.git/tree/bundles/org.eclipse.swt/Eclipse%20SWT%20PI/gtk/org/eclipse/swt/internal/gtk/OS.java#n85 for the code that's responsible for this (IMO somewhat misleading) exception (the else condition tries to load swt-pi4 on a non-GTK4 system if it can't load swt-pi3 but the failed attempt to load swt-pi3 is disguised by the way this try-catch block is written).

The edge snap works on Ubuntu 20.04 and 20.10 (as well as various non-Ubuntu systems like my Debian desktop). I am running 21.04 on my laptop at the moment for debugging this issue, and it is only on this release that it seems to have problems. If anyone reading has experienced this issue on a different release or distro please let me know.

The only real update I can give beyond that is to say that I am still working on it as and when I can.

**Comment by alculete** [comment] 2021-10-13 19:56
I've upgraded to 21.10 and the problem continues

**Comment by 0xjakob** [comment] 2021-11-24 07:25
I have the same issue on `master` when I build the snap myself (by changing it to devmode). I tried to fix it by stage-packaging any of the following packages:
* libglib2.0-0
* libgtk-3-0
* libswt-gtk-4-jav
* libswt-gtk-4-jni

But then I get a hard segfault as [we have reported in the eclipse bugzilla](https://bugs.eclipse.org/bugs/show_bug.cgi?id=577410). /~~Same thing happens if I create a link from the `libswt-pi3*` libs created by eclipse in the `~/.swt` folder.~~ Adding a symlink to `libswt-pi3` in the `~/.swt` folder as suggested in a [KaOS Forum](https://forum.kaosx.us/d/2358-error-with-eclipse), leads me to missing libgtk. If I install that, then I also get the hard segfault as above.

I'm on Ubuntu 20.04 and build the snap from master. As mentioned above, the only modification is `confinement: devmode` in order to build and install locally.

**Comment by lucyllewy** [comment] 2021-11-24 14:51
@0xjakob if your intention is to contribute to the development of this snap please don't change the confinement from `classic` to `devmode` when you build locally. That will cause your version to behave VERY differently to the version that is released to the snap store.

**Comment by 0xjakob** [comment] 2021-11-25 03:16
@diddledani Thanks for the clarification! My intention is to package a version of eclipse into a package, together with an SDK to allow a one-stop installation of [ESP-IDF](https://github.com/espressif/esp-idf) and corresponding [IDF Eclipse version](https://github.com/espressif/idf-eclipse-plugin). But so far we have the same problems as @alculete when we package our own version of eclipse (with devmode, though), hence me posting here.

I don't know though if we want to contribute here because `classic` confinement doesn't seem to be an option for us (no one-stop installation anymore).

**Comment by rloutrel** [comment] 2022-05-06 16:15
It seems, this issue should be closed and the remaining discussion "transferred" into #42 (or alternatively a new one?).

And if this ticket remains: what is the status here? I encounter the same problem with Ubuntu 22.04 (LTS => it will probably impact a lot of users)
My workspace in the previous system (Ubuntu 20.04 also LTS), is with the edge version and I wish I could avoid a regression to the 2019/stable Version.

I really which I can help, but do not know how.

I can specify:
- my ubuntu desktop installation is a fresh one (no dist-upgrade), using the "minimal" option (maybe some libs are not made available)

**Closed as completed** 2022-08-16 17:19 UTC
