### ISSUE TITLE
Opening eclipse causes GNOME to freeze.

### ISSUE THREAD

**Issue by mystiquewolf** [snapcrafters/eclipse#22] opened 2019-10-20 19:28 UTC
Mouse can be moved, but nothing responds to hover/click. From different console htop does not show high RAM or CPU usage, i have no idea what the problem might be caused by.

**Comment by mystiquewolf** [comment] 2019-10-20 19:29
Ubuntu 19.10, GNOME 3.34.1

**Comment by merlijn-sebrechts** [comment] 2022-12-08 22:59
Is this issue still present in the latest version?

**Comment by mystiquewolf** [comment] 2022-12-09 14:17
I don't know. Since then i've switched to KDE and i don't use both Eclipse and GNOME anymore.

**Comment by merlijn-sebrechts** [comment] 2022-12-09 14:45
Ok, I can't reproduce this on Ubuntu 22.04, and we've had a bunch of releases since you first reported so I'll close this issue for now.

Thanks for reporting!

**Closed as completed by merlijn-sebrechts** 2022-12-09 14:45 UTC
Labels: bug
